### ISSUE TITLE
cannot execute tests

### ISSUE THREAD

**Issue by massimilianokraus** [bradymholt/vuejs-test-mocha-typescript-example#1]
If I clone the repository, run `yarn install` and then `yarn test`, it gives me the following error:

module.js:557
    throw err;
    ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/mk/Science/Computer/tests/JavaScript/Vue/vue-test-1/node_modules/mocha-webpack/lib/webpack/compiler/createCompiler.js:8:16)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c cd ./test && ../node_modules/.bin/mocha-webpack --require ./support/domMocker.js --webpack-config ./support/webpack.config.js --recursive *.ts
Directory: /Users/mk/Science/Computer/tests/JavaScript/Vue/vue-test-1
Output:
".

I tried to add `webpack`, in the packages, then `typescript`, and then I updated the `ts-loader`, and then the `mocha-webpack`... keeps giving errors.

**Comment by bradymholt** [comment]
I just pushed up https://github.com/bradymholt/vuejs-test-mocha-typescript-example/commit/4ee92612fa836699be416916df91eaddf60c5344 which should fix this.
